### ISSUE TITLE
Descarga PDF

### ISSUE THREAD

**Issue by PachecoASIR** [PachecoASIR/ProyectoTiendaV2#29]
Al ejecutar todo el proyecto desde el netBeans todo funciona correctamente y a la hora de "Imprimir el ticket" este se imprime sin problemas. Ahora bien, cuando lo intentamos hacer desde el ejecutable no se crea el fichero.

**Comment by FranciscoFerreiraT** [comment]
![image](https://github.com/PachecoASIR/ProyectoTiendaV2/assets/92456485/32c0ecb3-edc4-4278-ac24-974a1711bb86)
Este es el error que nos sale al imprimir el ticket desde el ejecutable

**Comment by PachecoASIR** [comment]
La solución sería colocar la ruta absoluta pero habría que cambiarla por cada PC lo cual sería ineficaz. Otra posible solución sería que te lo guarde en C: directamente pero no se cuenta con permisos

**Comment by PachecoASIR** [comment]
Arreglado.
